CREATE TABLE users (
                       id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       email         VARCHAR(255) NOT NULL UNIQUE,
                       password_hash VARCHAR(255) NOT NULL,
                       name          VARCHAR(255) NOT NULL,
                       created_at    TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE workspaces (
                            id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name       VARCHAR(255) NOT NULL,
                            created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE memberships (
                             id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             user_id      BIGINT NOT NULL REFERENCES users (id),
                             workspace_id BIGINT NOT NULL REFERENCES workspaces (id),
                             role         VARCHAR(255) NOT NULL,
                             CONSTRAINT uq_membership_user_workspace UNIQUE (user_id, workspace_id)
);

CREATE TABLE projects (
                          id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          workspace_id BIGINT NOT NULL REFERENCES workspaces (id),
                          name         VARCHAR(255) NOT NULL,
                          created_at   TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE tasks (
                       id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       workspace_id BIGINT NOT NULL REFERENCES workspaces (id),
                       project_id   BIGINT NOT NULL REFERENCES projects (id),
                       title        VARCHAR(255) NOT NULL,
                       status       VARCHAR(255) NOT NULL,
                       assignee_id  BIGINT REFERENCES users (id),
                       created_at   TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_memberships_workspace ON memberships (workspace_id);
CREATE INDEX idx_projects_workspace ON projects (workspace_id);
CREATE INDEX idx_tasks_workspace_project ON tasks (workspace_id, project_id);